package com.sprintlite.sprintlite_backend.service;

import com.sprintlite.sprintlite_backend.domain.dto.request.InviteMemberRequest;
import com.sprintlite.sprintlite_backend.domain.dto.response.InviteResponse;
import com.sprintlite.sprintlite_backend.domain.dto.response.UserResponse;
import com.sprintlite.sprintlite_backend.domain.entity.Company;
import com.sprintlite.sprintlite_backend.domain.entity.Invitation;
import com.sprintlite.sprintlite_backend.domain.entity.Project;
import com.sprintlite.sprintlite_backend.domain.entity.User;
import com.sprintlite.sprintlite_backend.domain.mapper.UserMapper;
import com.sprintlite.sprintlite_backend.domain.repository.InvitationRepository;
import com.sprintlite.sprintlite_backend.domain.repository.ProjectMemberRepository;
import com.sprintlite.sprintlite_backend.domain.repository.ProjectRepository;
import com.sprintlite.sprintlite_backend.domain.repository.UserRepository;
import com.sprintlite.sprintlite_backend.exception.BadRequestException;
import com.sprintlite.sprintlite_backend.exception.ResourceNotFoundException;
import com.sprintlite.sprintlite_backend.security.SecurityUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class ProjectMemberService {
    
    private final ProjectRepository projectRepository;
    private final UserRepository userRepository;
    private final InvitationRepository invitationRepository;
    private final ProjectMemberRepository projectMemberRepository;
    private final UserMapper userMapper;
    private final SecurityUtils securityUtils;
    private final NotificationService notificationService;
    private final EmailService emailService;
    private final PasswordEncoder passwordEncoder;
    
    private static final String TEMP_PASSWORD_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%";
    
    @Transactional
    public InviteResponse inviteMembers(UUID projectId, InviteMemberRequest request) {
        User currentUser = securityUtils.getCurrentUser();
        
        if (!hasInvitePermission(currentUser)) {
            throw new BadRequestException("Only Project Managers and above can invite members");
        }
        
        Project project = projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found"));
        
        List<InviteResponse.InvitedUserInfo> invitedUsers = new ArrayList<>();
        List<String> failedEmails = new ArrayList<>();
        
        for (String email : request.getEmails()) {
            try {
                User existingUser = userRepository.findByEmail(email).orElse(null);
                
                if (existingUser != null) {
                    addMemberToProject(project, existingUser, request.getRole());
                    
                    InviteResponse.InvitedUserInfo info = InviteResponse.InvitedUserInfo.builder()
                            .email(email)
                            .isNewUser(false)
                            .invitationLink("/login")
                            .build();
                    invitedUsers.add(info);
                } else {
                    String tempPassword = generateTemporaryPassword();
                    String encodedPassword = passwordEncoder.encode(tempPassword);
                    
                    String token = UUID.randomUUID().toString();
                    Invitation invitation = Invitation.builder()
                            .company(currentUser.getCompany())
                            .project(project)
                            .invitedBy(currentUser)
                            .email(email)
                            .token(token)
                            .role(request.getRole())
                            .status("PENDING")
                            .autoGeneratedPassword(encodedPassword)
                            .passwordPlain(tempPassword)
                            .expiresAt(LocalDateTime.now().plusDays(7))
                            .build();
                    
                    invitationRepository.save(invitation);
                    
                    if (request.getSendEmail()) {
                        String invitationLink = "http://localhost:5173/accept-invitation?token=" + token;
                        emailService.sendInvitationEmail(email, currentUser.getFullName(), 
                                project.getName(), tempPassword, invitationLink, request.getMessage());
                    }
                    
                    InviteResponse.InvitedUserInfo info = InviteResponse.InvitedUserInfo.builder()
                            .email(email)
                            .temporaryPassword(tempPassword)
                            .invitationLink("/accept-invitation?token=" + token)
                            .isNewUser(true)
                            .build();
                    invitedUsers.add(info);
                }
            } catch (Exception e) {
                failedEmails.add(email);
            }
        }
        
        return InviteResponse.builder()
                .invitedUsers(invitedUsers)
                .failedEmails(failedEmails)
                .successCount(invitedUsers.size())
                .failedCount(failedEmails.size())
                .message(String.format("Successfully invited %d members", invitedUsers.size()))
                .build();
    }
    
    @Transactional
    public User acceptInvitation(String token, String firstName, String lastName, String newPassword) {
        Invitation invitation = invitationRepository.findByTokenAndStatus(token, "PENDING")
                .orElseThrow(() -> new BadRequestException("Invalid or expired invitation"));
        
        if (invitation.getExpiresAt().isBefore(LocalDateTime.now())) {
            invitation.setStatus("EXPIRED");
            invitationRepository.save(invitation);
            throw new BadRequestException("Invitation has expired");
        }
        
        User existingUser = userRepository.findByEmail(invitation.getEmail()).orElse(null);
        
        User user;
        if (existingUser != null) {
            user = existingUser;
            if (newPassword != null && !newPassword.isEmpty()) {
                user.setPasswordHash(passwordEncoder.encode(newPassword));
                user.setIsEmailVerified(true);
                userRepository.save(user);
            }
        } else {
            Company company = invitation.getCompany();
            String finalFirstName = (firstName != null && !firstName.isEmpty()) ? firstName : "New";
            String finalLastName = (lastName != null && !lastName.isEmpty()) ? lastName : "User";
            
            user = User.builder()
                    .email(invitation.getEmail())
                    .passwordHash(newPassword != null && !newPassword.isEmpty() ? 
                            passwordEncoder.encode(newPassword) : invitation.getAutoGeneratedPassword())
                    .firstName(finalFirstName)
                    .lastName(finalLastName)
                    .company(company)
                    .role(invitation.getRole())
                    .isActive(true)
                    .isEmailVerified(newPassword != null && !newPassword.isEmpty())
                    .build();
            user = userRepository.save(user);
            
            notificationService.sendWelcomeNotification(user, company);
        }
        
        addMemberToProject(invitation.getProject(), user, invitation.getRole());
        
        invitation.setStatus("ACCEPTED");
        invitation.setAcceptedAt(LocalDateTime.now());
        invitationRepository.save(invitation);
        
        return user;
    }
    
    public List<UserResponse> getProjectMembers(UUID projectId) {
        List<User> members = projectMemberRepository.findUsersByProjectId(projectId);
        return members.stream()
                .map(userMapper::toResponse)
                .collect(Collectors.toList());
    }
    
    @Transactional
    public void removeMember(UUID projectId, UUID userId) {
        User currentUser = securityUtils.getCurrentUser();
        
        if (!hasInvitePermission(currentUser)) {
            throw new BadRequestException("Only Project Managers and above can remove members");
        }
        
        projectMemberRepository.deleteByProjectIdAndUserId(projectId, userId);
    }
    
    @Transactional
    public UserResponse updateMemberRole(UUID projectId, UUID userId, String newRole) {
        User currentUser = securityUtils.getCurrentUser();
        
        if (!hasInvitePermission(currentUser)) {
            throw new BadRequestException("Only Project Managers and above can change roles");
        }
        
        projectMemberRepository.updateMemberRole(projectId, userId, newRole);
        
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));
        
        return userMapper.toResponse(user);
    }
    
    private void addMemberToProject(Project project, User user, String role) {
        boolean exists = projectMemberRepository.existsByProjectIdAndUserId(project.getId(), user.getId());
        if (!exists) {
            projectMemberRepository.addMember(project.getId(), user.getId(), role);
            notificationService.sendProjectJoinedNotification(project, user);
        }
    }
    
    private boolean hasInvitePermission(User user) {
        String role = user.getRole();
        return role.equals("COMPANY_ADMIN") || 
               role.equals("PROJECT_MANAGER") || 
               role.equals("TEAM_LEAD");
    }
    
    private String generateTemporaryPassword() {
        StringBuilder password = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            int index = (int) (Math.random() * TEMP_PASSWORD_CHARS.length());
            password.append(TEMP_PASSWORD_CHARS.charAt(index));
        }
        return password.toString();
    }
}